import { NextResponse } from 'next/server';
import { Innertube, UniversalCache } from 'youtubei.js';

export const dynamic = 'force-dynamic';

// Hot global caching to eliminate setup delays and YouTube rate limits.
// These variables persist in memory across serverless invocations on Vercel.
let ytInstance = null;
const streamCache = new Map(); // trackId -> { url, expires }

async function getInnertubeInstance() {
  if (!ytInstance) {
    ytInstance = await Innertube.create({
      cache: new UniversalCache(false),
      generate_session_locally: true
    });
  }
  return ytInstance;
}

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');

  if (!id) {
    return NextResponse.json({ error: 'Missing track ID' }, { status: 400 });
  }

  // 1. Hot Memory Cache Check (Instant redirect under 5ms if recently requested)
  const cachedStream = streamCache.get(id);
  if (cachedStream && cachedStream.expires > Date.now()) {
    console.log(`[AuraSynq Stream API]: Serving cached stream URL for track: ${id}`);
    return NextResponse.redirect(cachedStream.url);
  }

  // Ultimate Fallback Array: High availability proxy instances that support local=true
  // local=true is critical because it forces the Invidious server to pipe the audio bytes to the client.
  // Redirecting to raw googlevideo.com URLs generated by Vercel causes a 403 IP mismatch error on the client.
  const proxyInstances = [
    'https://invidious.nerdvpn.de',
    'https://invidious.protokolla.fi',
    'https://inv.nadeko.net',
    'https://invidious.tiekoetter.com',
    'https://invidious.f5.si'
  ];

  const fetchProxy = async (instance) => {
    // itag=140 is standard 128kbps m4a audio. local=true bypasses IP locks.
    const url = `${instance}/latest_version?id=${id}&itag=140&local=true`;
    // We use a GET request and just check the status to ensure the proxy is alive and the video exists.
    // Some proxies don't support HEAD properly, so we fetch just the headers with GET and abort.
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3500);
    
    try {
      const res = await fetch(url, { signal: controller.signal });
      clearTimeout(timeoutId);
      
      // If the proxy responds with 200 or 302, it works!
      if (res.ok || res.status === 302 || res.status === 307) {
        return url;
      }
      throw new Error("Proxy returned bad status: " + res.status);
    } catch (err) {
      clearTimeout(timeoutId);
      throw err;
    }
  };

  try {
    // Race all proxies in PARALLEL. The fastest valid response wins instantly.
    const bestUrl = await Promise.any(proxyInstances.map(fetchProxy));
    const expires = Date.now() + 2 * 60 * 60 * 1000;
    streamCache.set(id, { url: bestUrl, expires });
    console.log(`[AuraSynq Stream API]: Proxied audio via ${bestUrl}`);
    return NextResponse.redirect(bestUrl);
  } catch (e) {
    console.error('[AuraSynq Stream Error]: All streaming proxies failed simultaneously.');
    return NextResponse.json(
      { error: 'Audio extraction completely blocked. All proxy servers failed or video is restricted.' }, 
      { status: 500 }
    );
  }
}
